CFLAGS=-g
CAMLBYT=ocamlc $(CFLAGS)
CAMLBIN=ocamlopt $(CFLAGS)
CAMLLEX=ocamllex
CAMLYAC=ocamlyacc
MOCAC=mocac

LIBDEPS= 
OPTLIBDEPS= 

.PHONY: depend beforedepend default

default: all

depend : beforedepend
	 ocamldep *.ml *.mli > .depend

.SUFFIXES: .cmx .cmo .cmi .ml .mli  .mlm .mlms .mll .mly

.ml.cmo:
	$(CAMLBYT) -c  $<

.mli.cmi:
	$(CAMLBYT) -c  $<

.ml.cmx:
	$(CAMLBIN) -c  $<

.mll.cmo:
	$(CAMLLEX) $<
	$(CAMLBYT) -c  $*.ml

.mll.cmx:
	$(CAMLLEX) $<
	$(CAMLBIN) -c  $*.ml

.mly.cmo:
	$(CAMLYAC) $<
	$(CAMLBYT) -c  $*.mli
	$(CAMLBYT) -c  $*.ml

.mly.cmx:
	$(CAMLYAC) $<
	$(CAMLBIN) -c  $*.mli
	$(CAMLBIN) -c  $*.ml

.mly.cmi:
	$(CAMLYAC) $<
	$(CAMLBYT) -c  $*.mli

.mll.ml:
	$(CAMLLEX) $<

.mly.ml:
	$(CAMLYAC) $<

.mly.mli:
	$(CAMLYAC) $<

.mlm.ml:
	$(MOCAC) -c $<

.mlm.mli:
	$(MOCAC) -c $<

.mlms.ml:
	$(MOCAC) --sharing -c $<

.mlms.mli:
	$(MOCAC) --sharing $<
